name: Release Policy

on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Owner"
        required: true
        type: string
      repo:
        description: "Repository"
        required: true
        type: string
      tag:
        description: "Tag to release"
        required: true
        type: string
      artifacthub_pkg_path:
        description: "Path to the Artifact Hub package file"
        required: true
        default: "artifacthub-pkg.yml"
        type: string
      chart_dir:
        description: "Override the chart directory name (defaults to repo name if not provided)"
        required: false
        type: string
  repository_dispatch:
    types: [release-policy]

jobs:
  release-policy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract repository info
        id: repo-info
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "owner=${{ github.event.inputs.owner }}" >> $GITHUB_OUTPUT
            echo "repo=${{ github.event.inputs.repo }}" >> $GITHUB_OUTPUT
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "artifacthub_pkg_path=${{ github.event.inputs.artifacthub_pkg_path }}" >> $GITHUB_OUTPUT
            
            if [[ -n "${{ github.event.inputs.chart_dir }}" ]]; then
              echo "chart_dir=${{ github.event.inputs.chart_dir }}" >> $GITHUB_OUTPUT
            else
              echo "chart_dir=${{ github.event.inputs.repo }}" >> $GITHUB_OUTPUT
            fi
          else
            echo "owner=${{ github.event.client_payload.owner }}" >> $GITHUB_OUTPUT
            echo "repo=${{ github.event.client_payload.repo }}" >> $GITHUB_OUTPUT
            echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT

            if [[ -n "${{ github.event.client_payload.artifacthub_pkg_path }}" ]]; then
              echo "artifacthub_pkg_path=${{ github.event.client_payload.artifacthub_pkg_path }}" >> $GITHUB_OUTPUT
            else
              echo "artifacthub_pkg_path=artifacthub-pkg.yml" >> $GITHUB_OUTPUT
            fi
            
            if [[ -n "${{ github.event.client_payload.chart_dir }}" ]]; then
              echo "chart_dir=${{ github.event.client_payload.chart_dir }}" >> $GITHUB_OUTPUT
            else
              echo "chart_dir=${{ github.event.client_payload.repo }}" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Clone source repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ steps.repo-info.outputs.owner }}/${{ steps.repo-info.outputs.repo }}
          ref: ${{ steps.repo-info.outputs.tag }}
          path: policy-source

      - name: Clone source repository at artifacthub branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ steps.repo-info.outputs.owner }}/${{ steps.repo-info.outputs.repo }}
          ref: artifacthub
          path: policy-source-artifacthub

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "1.24"

      - name: Create directory structure
        run: |
          TARGET_DIR="charts/${{ steps.repo-info.outputs.chart_dir }}"
          mkdir -p "$TARGET_DIR"

          if [ ! -f "policy-source/README.md" ]; then
            echo "::error::README.md file not found in the source repository"
            exit 1
          fi

          if [ ! -f "policy-source/LICENSE" ]; then
            echo "::error::LICENSE file not found in the source repository"
            exit 1
          fi

          cp "policy-source/README.md" "$TARGET_DIR/"
          cp "policy-source/LICENSE" "$TARGET_DIR/"

          if [ -f "policy-source/questions-ui.yml" ]; then
            cp "policy-source/questions-ui.yml" "$TARGET_DIR/questions.yaml"
          else
            echo "::notice::questions-ui.yml file not found in the source repository"
          fi

      - name: Generate Chart.yaml
        run: |
          TARGET_DIR="charts/${{ steps.repo-info.outputs.chart_dir }}"
          ARTIFACTHUB_PKG_PATH="${{ steps.repo-info.outputs.artifacthub_pkg_path }}"

          cd pkg2chart

          go run main.go \
            --pkg "../policy-source-artifacthub/$ARTIFACTHUB_PKG_PATH" \
            --repo "../policy-source/artifacthub-repo.yml" \
            --output "../$TARGET_DIR/Chart.yaml"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: update policy ${{ steps.repo-info.outputs.repo }} to ${{ steps.repo-info.outputs.tag }}"
          body: |
            Updates policy ${{ steps.repo-info.outputs.repo }} to ${{ steps.repo-info.outputs.tag }}
          commit-message: "chore: update policy ${{ steps.repo-info.outputs.repo }} to ${{ steps.repo-info.outputs.tag }}"
          add-paths: |
            charts
          branch: update-policy-${{ steps.repo-info.outputs.repo }}-${{ steps.repo-info.outputs.tag }}
          base: main
          delete-branch: true
